<?php

namespace App\Http\Controllers;

class TestController extends Controller
{
    public function index()
    {
        $name    = 'Joe';
        $surname = 'Doe';

        // return view('test/test')->with('user', $name)->with('surname', $surname);

        // return view('test/test')->with(['user' => $name, 'surname' => $surname]);

        // return view('test/test', ['user' => $name, 'surname' => $surname]);

        $user = 'John';
        // return view('test/test', ['user' => $user, 'surname' => $surname]);

        /*
         *  Following array: ['user' => $user, 'surname' => $surname]
         *  can be generated by using method compact:
         *  compact('user', 'surname');
         */

        $lastname = 'Doe';

        $description = '<p>This is <strong>my</strong> description</p>';

        $age = 15;

        return view('test/test', compact('user', 'surname', 'description', 'age'));
    }
}
